baseURL: "https://TrungNgoVan.github.io/blog/"
languageCode: en-us
title: üê≥ I'm nvtrung
theme: PaperMod

params:
  author: Ngo Van Trung
  ShowReadingTime: true
  # ShowBreadCrumbs: true
  ShowShareButtons: true
  ShareButtons: ["facebook", "twitter"]
  enableEmoji: true
  enableInlineShortcodes: true
  Showtoc: true
  assets:
    favicon: "/blog/favicon.ico"
    favicon16x16: "/blog/favicon-16x16.png"
    favicon32x32: "/blog/favicon-32x32.png"
    apple_touch_icon: "/blog/apple-touch-icon.png"

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 1
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - identifier: about
      name: About
      url: /about/
      weight: 4
    - name: Github
      url: https://github.com/TrungNgoVan

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
